name: Create GitHub release
description: Creates a GitHub release from a tag

inputs:
  tag-name:
    description: Tag name
    required: true
  github-token:
    description: GitHub token
    required: true

runs:
  using: composite
  steps:
    - name: Create release
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          try {
            await github.rest.repos.createRelease({
              repo: context.repo.repo,
              owner: context.repo.owner,
              tag_name: ${{ inputs.github-token }},
            });
          } catch (error) {
            core.setFailed(error.message);
          }
